//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinterCRM.Areas.CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Events = new HashSet<Event>();
            this.Potentials = new HashSet<Potential>();
            this.Tasks = new HashSet<Task>();
        }
    
        public System.Guid Account_ID { get; set; }
        public string Account_Name { get; set; }
        public string Phone { get; set; }
        public string Account_Type { get; set; }
        public string Ownership { get; set; }
        public string Industry { get; set; }
        public Nullable<double> Employees { get; set; }
        public Nullable<double> Annual_Revenue { get; set; }
        public string Billing_Street { get; set; }
        public string Billing_City { get; set; }
        public string Billing_Country { get; set; }
        public string Billing_State { get; set; }
        public string Machines_Model { get; set; }
        public Nullable<double> Total_Spindles { get; set; }
        public Nullable<double> Total_machine { get; set; }
        public string Description { get; set; }
    
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Potential> Potentials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
