//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinterCRM.Areas.CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public System.Guid Call_Id { get; set; }
        public string Call_Owner_Id { get; set; }
        public string Subject { get; set; }
        public string Call_Type { get; set; }
        public string Call_Purpose { get; set; }
        public string Contact_Name { get; set; }
        public string What_Name { get; set; }
        public string Related_To { get; set; }
        public Nullable<double> Call_Start_Time { get; set; }
        public Nullable<double> Call_Duration { get; set; }
        public string Description { get; set; }
        public string Call_Result { get; set; }
    }
}
