//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinterCRM.Areas.CRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crmEntities : DbContext
    {
        public crmEntities()
            : base("name=crmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Call> Calls { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Potential> Potentials { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
