//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinterCRM.Areas.CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class machinedetail
    {
        public long id { get; set; }
        public Nullable<System.Guid> fk_Company { get; set; }
        public Nullable<System.Guid> Fk_Machine { get; set; }
        public Nullable<int> Spindles { get; set; }
        public string Description { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
