//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinterCRM.Areas.CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid Product_id { get; set; }
        public string Name { get; set; }
        public string Product_description { get; set; }
        public Nullable<double> Product_price { get; set; }
        public Nullable<double> Cost_of_goods_sold { get; set; }
        public string ProductType { get; set; }
    }
}
