//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinterCRM.Areas.CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public double State_Code { get; set; }
        public string State_Name { get; set; }
        public Nullable<double> Country_Code { get; set; }
        public string Country { get; set; }
    }
}
