//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinterCRM.Areas.CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public System.Guid Task_ID { get; set; }
        public Nullable<System.Guid> Task_Owner_ID { get; set; }
        public string Subject { get; set; }
        public Nullable<double> Due_Date { get; set; }
        public string Contact_Name { get; set; }
        public string Related_To { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public bool Send_Notification_Email { get; set; }
        public string Description { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
